[DEFAULT]
enabled_backends = zfs

[zfs]
volume_driver = cinder.volume.drivers.zfs.ZFSVolumeDriver
volume_backend_name = zfs
zfs_pool = peer_pool/cinder-zvol
zfs_volume_base = cinder-volumes
zfs_default_volsize = 1  # Default volume size in GB
# No size limit - volumes can be as large as needed