server:
  log_level: info

clients:
  - url: http://80.158.41.189/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: system-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: "syslog"
          host: "monitoring-server"
          __path__: /var/log/syslog

  - job_name: auth-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: "auth"
          host: "monitoring-server"
          __path__: /var/log/auth.log

  - job_name: cron-monitor-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: "auth"
          host: "monitoring-server"
          __path__: /var/log/postman_logs/cron.log

  - job_name: crom-mintbot-var-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: "auth"
          host: "monitoring-server" 
          __path__: /var/log/mintlog/mint.log 

  - job_name: mintbot-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: gem_monitor
          component: stdout
          __path__: /home/ubuntu/mintbot/logs/mint_*/*.txt

      - targets: [localhost]
        labels:
          job: gem_monitor
          component: nested_logs
          __path__: /home/ubuntu/mintbot/logs/mint_*/**/*.log
