name: Security Scan

on:
  pull_request:
    branches:
      - Dev
      - dev-1
  push:
    branches:
      - Dev
      - dev-1

jobs:
  gitleaks:
    name: Run Gitleaks Scan
    uses: peer-network/peer_global_security/.github/workflows/gitleaks.yml@main
    with:
      config: gitleaks.toml
